version: '3'
services:
  memcached:
    image: memcached:1.5-alpine
    ports:
      - "11211:11211"
      - "11211:11211/udp"
    network_mode: bridge

  test:
    build: .
    environment:
      - NEBULEX_MEMCACHED_HOST=memcached
    network_mode: bridge
    links:
      - memcached
