version: '3'
services:
  memcached:
    image: memcached:1.5-alpine
    ports:
      - '11211:11211'

  test:
    build:
      context: .
      args:
        MIX_ENV: test
    environment:
      - NEBULEX_MEMCACHED_HOST=memcached
    depends_on:
      - memcached
